version: "3.0"

services:
  db:
    image: postgres:11.7
    container_name: postgres-primer
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main